user root;
worker_processes 1;
events{}
http {

    server {
        listen 80;
        server_name localhost;

        # Фронтенд - статика React
        location / {
            proxy_pass http://frontend:3000/;
        }

        # Бэкенд - API прокси
        location /api/ {
            proxy_pass http://backend:5000/api/;
        }
    }
}