# Kustomize Base Configuration
# Use this for managing Kubernetes configurations with kustomize

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: learnreact

resources:
  - namespace.yml
  - configmap.yml
  - secrets.yml
  - nginx-configmap.yml
  - backend-deployment.yml
  - frontend-deployment.yml
  - backend-service.yml
  - frontend-service.yml
  - backend-hpa.yml
  - ingress.yml

commonLabels:
  app: learnreact
  managed-by: kustomize
